<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newwayofclap</name>
   <tag></tag>
   <elementGuidId>a46803e2-064f-4fc2-8942-6977436786b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[4]/div/div/div[2]/div/div/div/button)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[4]/div/div/div[2]/div/div/div/button)[1]</value>
   </webElementProperties>
</WebElementEntity>
